"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

const FOOTER_SECTIONS = [
  {
    title: "Company",
    links: [
      { href: "/wavetechlimited", label: "About" },
      { href: "/contact", label: "Contact" },
      { href: "/advertise", label: "Advertise" },
    ],
  },
  {
    title: "Legal",
    links: [
      { href: "/privacy", label: "Privacy Policy" },
      { href: "/terms", label: "Terms of Service" },
      { href: "/content-policy", label: "Content Policy" },
      { href: "/copyright", label: "Copyright" },
    ],
  },
  {
    title: "Resources",
    links: [
      { href: "/resources", label: "Resources" },
      { href: "/monetization-ready", label: "Monetization Checklist" },
      { href: "/seo", label: "AI Search Trends" },
    ],
  },
] as const;

export function SiteFooter() {
  const pathname = usePathname();
  const hideFooter = pathname?.startsWith("/studio") || pathname?.startsWith("/admin");

  if (hideFooter) return null;

  return (
    <footer className="app-shell px-4 pb-10 pt-8 text-[var(--foreground)] sm:px-8">
      <div className="mx-auto max-w-6xl">
        <div className="neon-panel rounded-3xl border border-[var(--panel-border)] bg-[var(--panel)]/88 p-6 sm:p-8">
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            <div className="space-y-3">
              <p className="text-xs uppercase tracking-[0.28em] text-[var(--muted)]">
                RafayGen AI
              </p>
              <p className="text-sm text-[var(--muted)] sm:text-base">
                WaveTech Limited builds RafayGen AI for chat, coding, reasoning, and media workflows.
                Public pages are designed for clear navigation and policy transparency.
              </p>
              <p className="text-sm text-[var(--muted)]">
                Support:{" "}
                <a
                  className="font-semibold text-[var(--foreground)] hover:underline"
                  href="mailto:support@wavetechlimited.com"
                >
                  support@wavetechlimited.com
                </a>
              </p>
            </div>

            {FOOTER_SECTIONS.map((section) => (
              <div key={section.title}>
                <p className="text-xs font-semibold uppercase tracking-[0.22em] text-[var(--muted)]">
                  {section.title}
                </p>
                <div className="mt-3 grid gap-2 text-sm text-[var(--muted)]">
                  {section.links.map((link) => (
                    <Link
                      key={link.href}
                      href={link.href}
                      className="hover:text-[var(--foreground)] hover:underline"
                    >
                      {link.label}
                    </Link>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--panel-border)] pt-4 text-xs text-[var(--muted)] sm:text-sm">
            <p>AI outputs are generated by automated systems and may require verification.</p>
            <p>© {new Date().getFullYear()} WaveTech Limited. All rights reserved.</p>
          </div>
        </div>
      </div>
    </footer>
  );
}
